import { Property, Agent, BlogPost, Testimonial } from './types';

export const agents: Agent[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@realestate.com',
    phone: '(555) 123-4567',
    image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'With over 8 years of experience in luxury real estate, Sarah specializes in helping clients find their dream homes in premium neighborhoods.',
    specialization: 'Luxury Residential',
    experience: 8,
    listings: 45,
    rating: 4.9,
    reviews: 127,
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@realestate.com',
    phone: '(555) 234-5678',
    image: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'Michael is a commercial real estate expert with a proven track record in helping businesses find the perfect location for growth.',
    specialization: 'Commercial Properties',
    experience: 12,
    listings: 38,
    rating: 4.8,
    reviews: 94,
  },
  {
    id: '3',
    name: 'Emma Rodriguez',
    email: 'emma.rodriguez@realestate.com',
    phone: '(555) 345-6789',
    image: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'Emma focuses on first-time homebuyers and rental properties, making the process smooth and stress-free for her clients.',
    specialization: 'First-Time Buyers & Rentals',
    experience: 5,
    listings: 62,
    rating: 4.7,
    reviews: 156,
  },
];

export const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Condo',
    price: 750000,
    location: {
      address: '123 Main Street, Unit 1205',
      city: 'New York',
      state: 'NY',
      zip: '10001',
      coordinates: { lat: 40.7128, lng: -74.0060 },
    },
    type: 'condo',
    category: 'buy',
    propertyClass: 'residential',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    yearBuilt: 2018,
    images: [
      'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Beautiful modern condo in the heart of downtown with stunning city views. Features high-end finishes, stainless steel appliances, and access to building amenities including gym and rooftop terrace.',
    features: ['City Views', 'Modern Kitchen', 'In-Unit Laundry', 'Gym Access', 'Rooftop Terrace', 'Concierge'],
    agent: agents[0],
    status: 'available',
    listedDate: '2024-01-15',
  },
  {
    id: '2',
    title: 'Charming Victorian House',
    price: 925000,
    location: {
      address: '456 Oak Avenue',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    type: 'house',
    category: 'buy',
    propertyClass: 'residential',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    yearBuilt: 1895,
    images: [
      'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Historic Victorian home with original details and modern updates. Beautiful hardwood floors, period moldings, and a private garden. Recently renovated kitchen and bathrooms.',
    features: ['Historic Details', 'Private Garden', 'Hardwood Floors', 'Renovated Kitchen', 'Period Moldings', 'Garage'],
    agent: agents[0],
    status: 'available',
    listedDate: '2024-01-10',
  },
  {
    id: '3',
    title: 'Luxury Penthouse Suite',
    price: 3500,
    location: {
      address: '789 Park Place, Penthouse',
      city: 'Miami',
      state: 'FL',
      zip: '33101',
      coordinates: { lat: 25.7617, lng: -80.1918 },
    },
    type: 'apartment',
    category: 'rent',
    propertyClass: 'residential',
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2800,
    yearBuilt: 2020,
    images: [
      'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2029722/pexels-photo-2029722.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2029685/pexels-photo-2029685.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Stunning penthouse with panoramic ocean views. Floor-to-ceiling windows, private terrace, and luxury amenities. Perfect for those seeking the ultimate Miami lifestyle.',
    features: ['Ocean Views', 'Private Terrace', 'Floor-to-Ceiling Windows', 'Pool Access', 'Beach Access', 'Concierge'],
    agent: agents[2],
    status: 'available',
    listedDate: '2024-01-20',
  },
  {
    id: '4',
    title: 'Office Space Downtown',
    price: 4500,
    location: {
      address: '321 Business Plaza, Suite 500',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      coordinates: { lat: 41.8781, lng: -87.6298 },
    },
    type: 'apartment',
    category: 'rent',
    propertyClass: 'commercial',
    bedrooms: 0,
    bathrooms: 2,
    sqft: 1800,
    yearBuilt: 2015,
    images: [
      'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Premium office space in the heart of Chicago\'s business district. Modern layout with conference rooms, reception area, and stunning city views.',
    features: ['Conference Rooms', 'Reception Area', 'City Views', 'Modern Layout', 'High-Speed Internet', 'Parking'],
    agent: agents[1],
    status: 'available',
    listedDate: '2024-01-12',
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: '2024 Real Estate Market Trends',
    excerpt: 'Discover the latest trends shaping the real estate market this year and what they mean for buyers and sellers.',
    content: 'The real estate market in 2024 is experiencing unprecedented changes...',
    image: 'https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Sarah Johnson',
    date: '2024-01-25',
    readTime: 8,
  },
  {
    id: '2',
    title: 'First-Time Buyer\'s Guide',
    excerpt: 'Everything you need to know about buying your first home, from financing to closing.',
    content: 'Buying your first home is an exciting milestone...',
    image: 'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Emma Rodriguez',
    date: '2024-01-20',
    readTime: 12,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'John Smith',
    image: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 5,
    review: 'Sarah helped us find our dream home in just two weeks. Her knowledge of the market and attention to detail made the process smooth and stress-free.',
    location: 'New York, NY',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    image: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 5,
    review: 'Michael\'s expertise in commercial real estate saved us both time and money. Highly recommend for any business looking for the perfect location.',
    location: 'Chicago, IL',
  },
  {
    id: '3',
    name: 'David Wilson',
    image: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 5,
    review: 'Emma made buying our first home an enjoyable experience. She explained everything clearly and was always available to answer our questions.',
    location: 'Miami, FL',
  },
];